# Use an existing docker image as a base
FROM nginx

# Set working directory
WORKDIR "/app"

# Copy files into container and install dependencies
COPY ./default.conf /etc/nginx/conf.d/default.conf
